@startuml erd
' tables.pu はこのファイルと同じディレクトリに存在している想定です。
!include tables.pu

Companies ||-|{ Books
Customers ||-|{ Orders

'下記中間テーブルです。
Books ||-||books_Authors
books_Authors ||-||Orders

Orders ||-|| Orders_Books
Orders_Books ||-|| Books

@enduml