@startuml erd
' tables.pu はこのファイルと同じディレクトリに存在している想定です。
!include tables.pu

Companies ||-|{ Books
Customers ||-|{ Orders
bookStock ||-|| Books
Books }O-||discount

'下記中間テーブルです。
reviews }-|| Books
reviews }-|| Customers
Books ||-||book_authors_mapping
book_authors_mapping ||-||Orders

Orders ||-|| orders_books_mapping
orders_books_mapping ||-|| Books

@enduml