@startuml
class Books {
    +id : string
    title : string
    price : int
}

Books : +id(PK)
Books : CompanieId(FK)

class Authors {
    +id : string
    name : string
}

Authors : +id(PK)

class books_Authors{
    +id : string
}

books_Authors : +id(PK)
books_Authors : bookId(FK)
books_Authors : authorId(FK)

class Companies{
    +id : string
    name : string
}

Companies : +id(PK)
Companies : bookId(FK)

class Customers{
    +id : string
    name : string
    address : string
    age : int
    gender : string 
}

Customers : +id(PK)
Customers : OrdersId(FK)

class Orders{
    +id : string
    createdAt : date
    totalAmount : int 
}

Orders : +id(PK)
Orders : customerId(FK)
Orders : bookId(FK)

class Orders_Books{
    +id : string
}

Orders_Books : +id(PK)
Orders_Books : bookId(FK)
Orders_Books : ordersId(FK)

@enduml