@startuml
class Books {
    +id : string
    title : string
    plice : int
}

Books : +id(PK)
Books : authorId(FK)
Books : companyId(FK)

class Authors {
    +id : string
    name : string
}

Authors : +id(PK)
Authors : bookId(FK)

class Companyes{
    +id : string
    name : string
}

Companyes : +id(PK)
Companyes : bookId(FK)

class Customers{
    +id : string
    name : string
    address : string
    age : int
    gender : string 
}

Customers : +id(PK)
Customers : oderId(FK)

class Oders{
    +id : string
}

Oders : +id(PK)
Oders : customerId(FK)
Oders : bookId(FK)
@enduml