@startuml
class Books {
    +id : string
    title : string
    price : int
}

Books : +id(PK)
Books : CompanyId(FK)
Books : discountId(FK)

class Authors {
    +id : string
    name : string
}

Authors : +id(PK)

class Companies{
    +id : string
    name : string
}

Companies : +id(PK)
Companies : bookId(FK)

class Customers{
    +id : string
    name : string
    address : string
    age : int
    gender : string 
}

Customers : +id(PK)
Customers : OrdersId(FK)

class Orders{
    +id : string
    createdAt : date
    totalAmount : int 
}

Orders : +id(PK)
Orders : customerId(FK)
Orders : bookId(FK)

class bookStock{
    +id : string
    stroks : int
}

bookStock : +id(PK)
bookStock : bookId(FK)

class discount{
    +id : string
    discountPrice : int
    start_at : date
    end_at : date
}

'下記中間テーブルです。
class reviews{
    +id : string
    massage : string
    createdAt : date
}

reviews : +id(PK)
reviews : bookId(FK)
reviews : customerId(FK)

class book_authors_mapping{
    +id : string
}

book_authors_mapping : +id(PK)
book_authors_mapping : bookId(FK)
book_authors_mapping : authorId(FK)


class orders_books_mapping{
    +id : string
}

orders_books_mapping : +id(PK)
orders_books_mapping : bookId(FK)
orders_books_mapping : ordersId(FK)

@enduml